{% set name = "pyo-oracle" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bio-oracle/pyo_oracle/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e9495bfdd1893e130b9433a68dc85b4795f8eabdbc898b0e1b677b0c9a163862

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - erddapy

test:
  imports:
    - pyo_oracle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bio-oracle/pyo_oracle
  summary: Python API client for the Bio-ORACLE ERDDAP server.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - vinisalazar
